import assert from 'node:assert/strict';
import { buildGeneratedPagePackage, renderGeneratedPage, renderPagePackageDialog } from '../src/ui/page-package-preview.js';

const records = [
  {
    id: 'ship.olympic',
    type: 'ship',
    title: 'RMS Olympic',
    summary: 'Lead ship of the Olympic class.',
    status: 'published',
    tags: ['Olympic class'],
    relationships: [
      { target: 'company.builder', relationship: 'built_by', confidence: 'verified', sourceIds: ['source.one'], note: '' },
      { target: 'company.line', relationship: 'operated_by', confidence: 'verified', sourceIds: ['source.one'], note: '' }
    ],
    sources: [{ id: 'source.one', title: 'Builder records', type: 'archive' }],
    data: { builder: 'company.builder', operator: 'company.line', launchDate: '1910-10-20', maidenVoyage: '1911-06-14', grossTonnage: '45,324 GRT' },
    metadata: { confidence: 'verified', reviewed: '2026-07-25' }
  },
  { id: 'company.builder', type: 'company', title: 'Harland and Wolff', summary: 'Builder.', status: 'published', tags: ['Shipbuilder'], relationships: [], sources: [{ id: 'source.one', title: 'Builder records' }], data: { country: 'United Kingdom', founded: '1861', yard: 'Queen’s Island' }, metadata: { confidence: 'verified', reviewed: '2026-07-25' } },
  { id: 'company.line', type: 'company', title: 'White Star Line', summary: 'Operator.', status: 'published', tags: ['Shipping line'], relationships: [], sources: [{ id: 'source.one', title: 'Builder records' }], data: { country: 'United Kingdom', founded: '1845', routeFocus: 'North Atlantic' }, metadata: { confidence: 'verified', reviewed: '2026-07-25' } },
  { id: 'source.one', type: 'source', title: 'Builder records', summary: 'Primary documentation.', status: 'published', tags: [], relationships: [], sources: [], data: { citation: 'Builder archive records.' }, metadata: { confidence: 'verified', reviewed: '2026-07-25' } }
];

const pagePackage = buildGeneratedPagePackage(records[0], records);
assert.equal(pagePackage.format, 'curatoros-generated-page-package');
assert.equal(pagePackage.filename, 'ship.olympic.html');
assert.match(pagePackage.html, /<!doctype html>/i);
assert.match(pagePackage.html, /RMS Olympic/);
assert.match(pagePackage.html, /Generated by CuratorOS/);
assert.match(pagePackage.html, /application\/ld\+json/);
assert.equal(pagePackage.publication.record.id, 'ship.olympic');

const html = renderGeneratedPage(pagePackage.publication);
assert.match(html, /Canonical details/);
assert.match(html, /Harland and Wolff/);
assert.match(html, /Builder records/);

const dialog = renderPagePackageDialog(records, 'ship.olympic');
assert.match(dialog, /Generated page package/);
assert.match(dialog, /data-download-page-package/);
assert.match(dialog, /srcdoc=/);

assert.throws(() => buildGeneratedPagePackage({ ...records[0], summary: '' }, records), /Publication is blocked/);

console.log('Generated page package tests passed.');
