const CR_KEY='curatoros.research.conclusions';
const CR_CATALOG='curatoros.rebuilt.catalog';
const crButton=document.querySelector('#conclusion-review');
const crApp=document.querySelector('#app');
let crFilter='candidate';
crButton?.addEventListener('click',()=>{crActivate();crRender();});
function crActivate(){document.querySelectorAll('.nav .active').forEach(x=>x.classList.remove('active'));crButton?.classList.add('active')}
function crJson(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}}
function crWrite(k,v){localStorage.setItem(k,JSON.stringify(v))}
function crItems(){const v=crJson(CR_KEY,[]);return Array.isArray(v)?v:[]}
function crRecords(){const v=crJson(CR_CATALOG,[]);return Array.isArray(v)?v:[]}
function crTitle(r){return r?.title||r?.name||r?.id||'Untitled record'}
function crRender(){if(!crApp)return;const items=crItems(),visible=items.filter(x=>crFilter==='all'||(x.status||'candidate')===crFilter),accepted=items.filter(x=>x.status==='accepted').length,returned=items.filter(x=>x.status==='returned').length,dismissed=items.filter(x=>x.status==='dismissed').length;crApp.innerHTML=`<section class="panel conclusion-review-hero"><span class="eyebrow">Curatorial decision layer</span><h3>Conclusion Review</h3><p>Review supported conclusions after investigation and decide whether they are ready to proceed toward a knowledge destination. Approval here records a curatorial decision; it does not automatically alter canonical records.</p></section><section class="metrics"><div class="metric"><strong>${items.filter(x=>(x.status||'candidate')==='candidate').length}</strong><span>Awaiting review</span></div><div class="metric"><strong>${accepted}</strong><span>Accepted</span></div><div class="metric"><strong>${returned}</strong><span>Returned</span></div><div class="metric"><strong>${dismissed}</strong><span>Dismissed</span></div></section><section class="panel conclusion-review-controls"><label><span>Show</span><select id="cr-filter"><option value="candidate">Awaiting review</option><option value="accepted">Accepted</option><option value="returned">Returned</option><option value="dismissed">Dismissed</option><option value="all">All</option></select></label></section><section class="panel"><div class="conclusion-review-list">${visible.length?visible.map(crCard).join(''):'<p class="empty">No conclusion candidates match this view.</p>'}</div></section>`;const f=document.querySelector('#cr-filter');if(f)f.value=crFilter;f?.addEventListener('change',e=>{crFilter=e.target.value;crRender()});document.querySelectorAll('[data-cr-status]').forEach(b=>b.onclick=()=>crSetStatus(b.dataset.crId,b.dataset.crStatus));document.querySelectorAll('[data-cr-open]').forEach(b=>b.onclick=()=>crOpenRecord(b.dataset.crOpen));}
function crCard(x){const records=crRecords(),byId=new Map(records.map(r=>[r.id,r])),target=x.targetRecordId?byId.get(x.targetRecordId):null,status=x.status||'candidate';return `<article class="conclusion-review-card"><div class="badges"><span class="badge">${crEsc(crLabel(status))}</span><span class="badge">${crEsc(crLabel(x.destination||'unrouted'))}</span></div><h4>${crEsc(x.conclusion||'Untitled conclusion')}</h4><dl><div><dt>Research question</dt><dd>${crEsc(x.question||'—')}</dd></div><div><dt>Intended destination</dt><dd>${crEsc(crLabel(x.destination||'—'))}</dd></div><div><dt>Target record</dt><dd>${crEsc(target?crTitle(target):(x.targetRecordId||'No single target'))}</dd></div><div><dt>Routing note</dt><dd>${crEsc(x.note||'—')}</dd></div></dl><div class="conclusion-review-actions">${x.targetRecordId?`<button data-cr-open="${crEsc(x.targetRecordId)}">Open target record</button>`:''}${status!=='accepted'?`<button data-cr-status="accepted" data-cr-id="${crEsc(x.id)}">Accept candidate</button>`:''}${status!=='returned'?`<button data-cr-status="returned" data-cr-id="${crEsc(x.id)}">Return to investigation</button>`:''}${status!=='dismissed'?`<button data-cr-status="dismissed" data-cr-id="${crEsc(x.id)}">Dismiss candidate</button>`:''}</div>${x.reviewedAt?`<small>Last review decision: ${crEsc(new Date(x.reviewedAt).toLocaleString())}</small>`:''}</article>`}
function crSetStatus(id,status){const now=new Date().toISOString();crWrite(CR_KEY,crItems().map(x=>x.id===id?{...x,status,reviewedAt:now}:x));crRender()}
function crOpenRecord(id){sessionStorage.setItem('curatoros.openRecordId',id);sessionStorage.setItem('curatoros.recordFieldFocus',JSON.stringify({recordId:id,field:'',label:'Conclusion Review',kind:'research-conclusion',requestedAt:new Date().toISOString()}));window.CuratorOSNavigate?.open?.('records')}
function crLabel(v){return String(v||'').replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
function crEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
