const IR_PACKAGES='curatoros.knowledge.promotions';
const IR_CATALOG='curatoros.rebuilt.catalog';
const IR_CHANGES='curatoros.project.pendingChanges';
const IR_BASELINE='curatoros.project.editBaseline';
const IR_LEDGER='curatoros.evidence.ledger';
const IR_REL='curatoros.relationship.acceptedProposals';
const IR_PUBLICATION='curatoros.publication.researchNotes';
const irButton=document.querySelector('#incorporation-review');
const irApp=document.querySelector('#app');
let irFilter='ready';
irButton?.addEventListener('click',()=>{irActivate();irRender();});
function irActivate(){document.querySelectorAll('.nav .active').forEach(x=>x.classList.remove('active'));irButton?.classList.add('active')}
function irJson(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}}
function irWrite(k,v){localStorage.setItem(k,JSON.stringify(v))}
function irPackages(){const v=irJson(IR_PACKAGES,[]);return Array.isArray(v)?v:[]}
function irRecords(){const v=irJson(IR_CATALOG,[]);return Array.isArray(v)?v:[]}
function irTitle(r){return r?.title||r?.name||r?.id||'Untitled record'}
function irRender(){if(!irApp)return;const packages=irPackages(),visible=packages.filter(p=>irFilter==='all'||(irFilter==='ready'?(p.status==='ready'):(p.status==='incorporated'))),ready=packages.filter(p=>p.status==='ready').length,done=packages.filter(p=>p.status==='incorporated').length;irApp.innerHTML=`<section class="panel ir-hero"><span class="eyebrow">Final knowledge gate</span><h3>Incorporation Review</h3><p>Review promotion packages that have already passed discovery, investigation, conclusion review, and knowledge promotion. Nothing enters a CuratorOS knowledge workflow from here without an explicit final confirmation.</p><div class="ir-stat"><strong>${ready}</strong><span>ready for incorporation</span></div><div class="ir-stat"><strong>${done}</strong><span>incorporated</span></div></section><section class="panel ir-controls"><label><span>Show</span><select id="ir-filter"><option value="ready">Ready</option><option value="incorporated">Incorporated</option><option value="all">All packages</option></select></label></section><section class="panel"><div class="ir-list">${visible.length?visible.map(irCard).join(''):'<p class="empty">No promotion packages match this view.</p>'}</div></section>`;const f=document.querySelector('#ir-filter');if(f)f.value=irFilter;f?.addEventListener('change',e=>{irFilter=e.target.value;irRender()});document.querySelectorAll('[data-ir-incorporate]').forEach(b=>b.onclick=()=>irIncorporate(b.dataset.irIncorporate));document.querySelectorAll('[data-ir-open]').forEach(b=>b.onclick=()=>irOpenRecord(b.dataset.irOpen));}
function irCard(p){const records=irRecords(),byId=new Map(records.map(r=>[r.id,r])),target=p.targetRecordId?byId.get(p.targetRecordId):null;return `<article class="ir-card" data-ir-package="${irEsc(p.id)}"><div class="badges"><span class="badge">${irEsc(irLabel(p.destination))}</span><span class="badge">${irEsc(irLabel(p.status||'prepared'))}</span></div><h4>${irEsc(p.conclusion||p.details?.value||'Untitled promotion')}</h4><dl><div><dt>Research question</dt><dd>${irEsc(p.question||'—')}</dd></div><div><dt>Target</dt><dd>${irEsc(target?irTitle(target):(p.targetRecordId||'No single Ship Record'))}</dd></div><div><dt>Proposed incorporation</dt><dd>${irEsc(irProposal(p))}</dd></div><div><dt>Provenance</dt><dd>${irEsc(`Conclusion ${p.conclusionId||'—'} · Research task ${p.taskId||'—'}`)}</dd></div></dl><div class="ir-actions">${p.targetRecordId?`<button type="button" data-ir-open="${irEsc(p.targetRecordId)}">Open target Ship Record</button>`:''}${p.status==='ready'?`<button type="button" class="primary" data-ir-incorporate="${irEsc(p.id)}">Incorporate as pending knowledge</button>`:''}</div>${p.incorporatedAt?`<small>Incorporated ${irEsc(new Date(p.incorporatedAt).toLocaleString())}${p.result?.kind?` · ${irEsc(irLabel(p.result.kind))}`:''}</small>`:''}</article>`}
function irProposal(p){const d=p.details||{};if(p.destination==='ship-record')return `${d.field||'field'} → ${d.value||''}`;if(p.destination==='evidence')return `Evidence claim for ${d.field||'unspecified field'}: ${d.value||''}`;if(p.destination==='relationship')return `${d.field||'relationship'}: ${d.value||''}`;return d.value||p.conclusion||''}
function irIncorporate(id){const packages=irPackages(),i=packages.findIndex(p=>p.id===id);if(i<0)return;const p=packages[i];if(p.status!=='ready')return alert('Only packages marked Ready for incorporation can be incorporated.');const target=p.targetRecordId?irRecords().find(r=>r.id===p.targetRecordId):null;const message=`Final incorporation check\n\nDestination: ${irLabel(p.destination)}\n${target?`Target: ${irTitle(target)}\n`:''}Proposed knowledge: ${p.details?.value||p.conclusion||''}\n\nThis will enter the appropriate CuratorOS knowledge workflow with provenance preserved. Continue?`;if(!confirm(message))return;let result;try{result=irApply(p)}catch(err){alert(err?.message||String(err));return}const now=new Date().toISOString();packages[i]={...p,status:'incorporated',incorporatedAt:now,updatedAt:now,result};irWrite(IR_PACKAGES,packages);window.dispatchEvent(new CustomEvent('curatoros:records-changed'));irRender();alert('Knowledge incorporated into its CuratorOS workflow. Provenance was preserved.')}
function irApply(p){if(p.destination==='ship-record')return irApplyRecord(p);if(p.destination==='evidence')return irApplyEvidence(p);if(p.destination==='relationship')return irApplyRelationship(p);return irApplyPublication(p)}
function irApplyRecord(p){if(!p.targetRecordId)throw new Error('A Ship Record target is required.');const field=String(p.details?.field||'').trim(),value=p.details?.value;if(!field)throw new Error('Choose a target Ship Record field before incorporation.');const all=irRecords(),idx=all.findIndex(r=>r.id===p.targetRecordId);if(idx<0)throw new Error('The target Ship Record no longer exists.');const before=JSON.parse(JSON.stringify(all[idx])),after=JSON.parse(JSON.stringify(before));if(field==='summary')after.summary=value;else{after.data=after.data||{};after.data[field]=value}after.metadata={...(after.metadata||{}),knowledgePromotion:{packageId:p.id,conclusionId:p.conclusionId,taskId:p.taskId,incorporatedAt:new Date().toISOString()}};if(!localStorage.getItem(IR_BASELINE))irWrite(IR_BASELINE,all);all[idx]=after;irWrite(IR_CATALOG,all);const changes=irJson(IR_CHANGES,[]);changes.push({id:`change:promotion:${p.id}`,recordId:after.id,title:after.title||after.name||after.id,changedAt:new Date().toISOString(),before,after,fields:[field],changeKind:'research-promotion',provenance:p.provenance||{conclusionId:p.conclusionId,researchTaskId:p.taskId}});irWrite(IR_CHANGES,changes);return{kind:'pending-record-change',recordId:after.id,field}}
function irApplyEvidence(p){if(!p.targetRecordId)throw new Error('A target Ship Record is required for an evidence claim.');const field=String(p.details?.field||'').trim();if(!field)throw new Error('Choose the field this evidence supports.');const claims=irJson(IR_LEDGER,[]),now=new Date().toISOString();const claim={id:`claim:research:${Date.now()}`,recordId:p.targetRecordId,field,value:p.details?.value||p.conclusion||'',rawValue:p.details?.value||p.conclusion||'',rawLabel:'Research conclusion',confidence:'reviewed',source:{kind:'research-conclusion',promotionPackageId:p.id,conclusionId:p.conclusionId,researchTaskId:p.taskId},observedAt:now,approvedAt:now,preferred:false,resolutionNote:p.details?.note||p.routingNote||''};claims.push(claim);irWrite(IR_LEDGER,claims);return{kind:'evidence-claim',claimId:claim.id}}
function irApplyRelationship(p){const list=irJson(IR_REL,[]),item={id:`relationship-proposal:${Date.now()}`,status:'accepted',recordId:p.targetRecordId||'',relationshipType:p.details?.field||'',statement:p.details?.value||p.conclusion||'',note:p.details?.note||p.routingNote||'',promotionPackageId:p.id,conclusionId:p.conclusionId,researchTaskId:p.taskId,acceptedAt:new Date().toISOString()};list.push(item);irWrite(IR_REL,list);return{kind:'accepted-relationship-proposal',proposalId:item.id}}
function irApplyPublication(p){const list=irJson(IR_PUBLICATION,[]),item={id:`publication-note:${Date.now()}`,status:'available',text:p.details?.value||p.conclusion||'',suggestedUse:p.details?.note||'',targetRecordId:p.targetRecordId||'',promotionPackageId:p.id,conclusionId:p.conclusionId,researchTaskId:p.taskId,createdAt:new Date().toISOString()};list.push(item);irWrite(IR_PUBLICATION,list);return{kind:'publication-research-note',noteId:item.id}}
function irOpenRecord(id){sessionStorage.setItem('curatoros.openRecordId',id);sessionStorage.setItem('curatoros.recordFieldFocus',JSON.stringify({recordId:id,field:'',label:'Incorporation Review',kind:'knowledge-incorporation',requestedAt:new Date().toISOString()}));window.CuratorOSNavigate?.open?.('records')}
function irLabel(v){return String(v||'').replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}function irEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
