const STORAGE={catalog:'curatoros.rebuilt.catalog',handled:'curatoros.rebuilt.handled',scanFindings:'curatoros.rebuilt.scanFindings'};
const seedRecords=[
{id:'ship.olympic',type:'ship',title:'RMS Olympic',status:'published',sources:[{id:'source.builder-records'}],data:{builder:'Harland and Wolff',operator:'White Star Line',launchDate:'1910-10-20'}},
{id:'company.white-star-line',type:'company',title:'White Star Line',status:'review',sources:[{id:'source.builder-records'}],data:{country:'United Kingdom'}},
{id:'company.harland-wolff',type:'company',title:'Harland and Wolff',status:'review',sources:[{id:'source.builder-records'}],data:{country:'United Kingdom'}},
{id:'object.olympic-menu-1929',type:'object',title:'RMS Olympic Breakfast Menu',status:'review',sources:[],data:{category:'menu',date:'1929-06-02'}},
{id:'photo.olympic-profile',type:'photo',title:'RMS Olympic profile view',status:'review',sources:[],data:{depictedSubject:'ship.olympic',rights:'Reference use only.'}}
];
const state={view:'findings',status:'open',category:'',severity:'',search:'',notice:''};
let records=readJson(STORAGE.catalog,seedRecords);
let scanFindings=readJson(STORAGE.scanFindings,[]);
let handled=new Set(readJson(STORAGE.handled,[]));
const app=document.querySelector('#app');
const fileInput=document.querySelector('#catalog-file');
const scanInput=document.querySelector('#scan-file');

document.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>{state.view=btn.dataset.view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===btn));render();}));
document.querySelector('#quick-backup').addEventListener('click',backup);
document.querySelector('#command').addEventListener('click',()=>{const choice=prompt('Open: findings, records, or help');if(!choice)return;const value=choice.trim().toLowerCase();if(['findings','records','help'].includes(value)){state.view=value;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===value));render();}});
document.querySelector('#load-catalog').addEventListener('click',()=>fileInput.click());
document.querySelector('#import-scan').addEventListener('click',()=>scanInput.click());
fileInput.addEventListener('change',importCatalog);
scanInput.addEventListener('change',importScan);

function render(){if(state.view==='records')return renderRecords();if(state.view==='help')return renderHelp();renderFindings();}
function renderFindings(){const all=buildFindings(records);const pool=state.status==='handled'?all.filter(x=>handled.has(x.id)):all.filter(x=>!handled.has(x.id));const visible=pool.filter(x=>(!state.category||x.category===state.category)&&(!state.severity||x.severity===state.severity)&&(!state.search||haystack(x).includes(state.search.toLowerCase())));const categories=[...new Set(all.map(x=>x.category))].sort();app.innerHTML=`${state.notice?`<div class="notice">${esc(state.notice)}</div>`:''}<section class="panel hero"><div><span class="eyebrow">Actionable site maintenance</span><h3>${pool.length} ${state.status} finding${pool.length===1?'':'s'}</h3><p>Plain controls, direct listeners, no synthetic clicks, no touch bridge.</p></div><div class="toolbar"><button id="open-findings" class="${state.status==='open'?'active':''}">Open</button><button id="handled-findings" class="${state.status==='handled'?'active':''}">Handled</button></div></section><section class="metrics">${metric(all.filter(x=>x.category==='unsourced').length,'Missing sources')}${metric(all.filter(x=>x.category==='metadata').length,'Missing metadata')}${metric(all.filter(x=>x.category==='review').length,'Needs review')}${metric(scanFindings.length,'Imported scan findings')}</section><section class="panel"><div class="filters"><input id="search" type="search" placeholder="Search page, ship, record, or issue…" value="${esc(state.search)}"><select id="category"><option value="">All categories</option>${categories.map(c=>`<option value="${esc(c)}"${state.category===c?' selected':''}>${esc(label(c))}</option>`).join('')}</select><select id="severity"><option value="">All priorities</option>${['high','medium','low'].map(s=>`<option value="${s}"${state.severity===s?' selected':''}>${label(s)}</option>`).join('')}</select><button id="clear">Clear filters</button></div><div class="summary">Showing ${visible.length} of ${pool.length} ${state.status} findings.</div><div class="findings">${visible.length?visible.map(renderFinding).join(''):'<div class="empty">No findings match these filters.</div>'}</div></section>`;document.querySelector('#open-findings').addEventListener('click',()=>{state.status='open';renderFindings();});document.querySelector('#handled-findings').addEventListener('click',()=>{state.status='handled';renderFindings();});document.querySelector('#search').addEventListener('input',e=>{state.search=e.target.value;refreshFindingList();});document.querySelector('#category').addEventListener('change',e=>{state.category=e.target.value;renderFindings();});document.querySelector('#severity').addEventListener('change',e=>{state.severity=e.target.value;renderFindings();});document.querySelector('#clear').addEventListener('click',()=>{state.search='';state.category='';state.severity='';renderFindings();});document.querySelectorAll('[data-handle]').forEach(btn=>btn.addEventListener('click',()=>toggleHandled(btn.dataset.handle)));}
function refreshFindingList(){const all=buildFindings(records);const pool=state.status==='handled'?all.filter(x=>handled.has(x.id)):all.filter(x=>!handled.has(x.id));const visible=pool.filter(x=>(!state.category||x.category===state.category)&&(!state.severity||x.severity===state.severity)&&(!state.search||haystack(x).includes(state.search.toLowerCase())));const list=document.querySelector('.findings');const summary=document.querySelector('.summary');if(summary)summary.textContent=`Showing ${visible.length} of ${pool.length} ${state.status} findings.`;if(list){list.innerHTML=visible.length?visible.map(renderFinding).join(''):'<div class="empty">No findings match these filters.</div>';list.querySelectorAll('[data-handle]').forEach(btn=>btn.addEventListener('click',()=>toggleHandled(btn.dataset.handle)));}}
function renderRecords(){app.innerHTML=`<section class="panel"><span class="eyebrow">Knowledge records</span><h3>${records.length} local record${records.length===1?'':'s'}</h3><div class="findings">${records.map(r=>`<article class="finding"><div class="finding-head"><div><div class="badges"><span class="badge">${esc(r.type||'record')}</span><span class="badge">${esc(r.status||'unknown')}</span></div><h4>${esc(r.title||r.id)}</h4></div></div><p>${esc(r.id)}</p></article>`).join('')}</div></section>`;}
function renderHelp(){app.innerHTML=`<section class="panel"><span class="eyebrow">Rebuilt interface</span><h3>Designed for iPad Safari first</h3><p>This page uses native HTML controls with direct event listeners. It intentionally avoids delegated touch routing, synthetic clicks, global button interception, and full-page replacement while typing.</p><p>Use Load catalog to replace the local records, Import scan to add labeled external findings, and Quick Backup to save the current local catalog and imported scan findings.</p></section>`;}
function buildFindings(items){const out=[];for(const r of items){const title=r.title||r.id;if(!(r.sources||[]).length)out.push(finding(r,'unsourced','high',`${title} has no direct source attached.`,'Add at least one source or curatorial note.'));if(['review','draft'].includes(r.status))out.push(finding(r,'review',r.status==='draft'?'high':'medium',`${title} is marked ${r.status}.`,'Review evidence and metadata before publication.'));const missing=[];if(!r.title)missing.push('title');if(!r.type)missing.push('type');if(!r.status)missing.push('status');if(r.type==='ship'){if(!r.data?.builder)missing.push('builder');if(!r.data?.operator)missing.push('operator');if(!r.data?.launchDate)missing.push('launch date');}if(missing.length)out.push(finding(r,'metadata','medium',`${title} is missing ${missing.join(', ')}.`,'Complete the missing fields.'));}return dedupe([...out,...scanFindings]);}
function finding(r,category,severity,summary,recommendation){return{id:`${r.id}:${category}`,recordId:r.id,title:r.title||r.id,category,severity,summary,recommendation,sourceType:'catalog'};}
function renderFinding(x){return`<article class="finding ${esc(x.severity)}"><div class="finding-head"><div><div class="badges"><span class="badge">${esc(label(x.category))}</span><span class="badge">${esc(label(x.severity))} priority</span>${x.sourceType?`<span class="badge">${esc(label(x.sourceType))}</span>`:''}</div><h4>${esc(x.title)}</h4></div></div><p>${esc(x.summary)}</p>${x.context?`<p><strong>Context:</strong> ${esc(x.context)}</p>`:''}<p><strong>Recommended action:</strong> ${esc(x.recommendation)}</p>${x.pageUrl||x.targetUrl||x.replacementUrl?`<div class="actions">${x.pageUrl?`<a href="${esc(x.pageUrl)}" target="_blank" rel="noopener">Open page</a>`:''}${x.targetUrl?`<a href="${esc(x.targetUrl)}" target="_blank" rel="noopener">Open checked URL</a>`:''}${x.replacementUrl?`<a href="${esc(x.replacementUrl)}" target="_blank" rel="noopener">Open replacement</a>`:''}</div>`:''}<div class="actions"><button data-handle="${esc(x.id)}">${handled.has(x.id)?'Reopen':'Mark handled'}</button></div></article>`;}
function toggleHandled(id){handled.has(id)?handled.delete(id):handled.add(id);localStorage.setItem(STORAGE.handled,JSON.stringify([...handled]));state.notice=handled.has(id)?'Finding marked handled.':'Finding reopened.';renderFindings();}
async function importCatalog(){const file=fileInput.files?.[0];if(!file)return;try{const value=JSON.parse(await file.text());const next=Array.isArray(value?.records)?value.records:Array.isArray(value)?value:null;if(!next)throw new Error('Choose a CuratorOS catalog JSON file.');records=next;localStorage.setItem(STORAGE.catalog,JSON.stringify(records));state.notice=`Loaded ${records.length} records from ${file.name}.`;render();}catch(err){alert(err.message||String(err));}finally{fileInput.value='';}}
async function importScan(){const file=scanInput.files?.[0];if(!file)return;try{const text=await file.text();const raw=file.name.toLowerCase().endsWith('.csv')?parseCsvFindings(text):parseJsonFindings(JSON.parse(text));const imported=raw.map((x,i)=>normalizeScanFinding(x,i,file.name)).filter(Boolean);scanFindings=dedupe([...scanFindings,...imported]);localStorage.setItem(STORAGE.scanFindings,JSON.stringify(scanFindings));state.notice=`Imported ${imported.length} labeled scan finding${imported.length===1?'':'s'} from ${file.name}.`;render();}catch(err){alert(err.message||String(err));}finally{scanInput.value='';}}
function parseJsonFindings(value){if(Array.isArray(value))return value;if(Array.isArray(value?.findings))return value.findings;if(Array.isArray(value?.rows))return value.rows;if(Array.isArray(value?.results))return value.results;return[];}
function normalizeScanFinding(row,index,fileName){const x=Object.fromEntries(Object.entries(row||{}).map(([k,v])=>[String(k).trim().toLowerCase(),v]));const category=normalizeCategory(x.category||x.type||x.issue_type||x.kind||'imported');const severity=normalizeSeverity(x.severity||x.priority,x.status,category);const pageUrl=x.page_url||x.page||x.source_url||x.source_page||'';const targetUrl=x.target_url||x.checked_url||x.url||x.target||x.link||'';const replacementUrl=x.replacement_url||x.final_url||x.replacement||'';const title=x.title||x.page_title||x.issue||x.message||x.summary||targetUrl||pageUrl||`Imported finding ${index+1}`;const summary=x.summary||x.message||x.detail||x.error||x.description||`${label(category)} finding${targetUrl?` for ${targetUrl}`:''}.`;const recommendation=x.recommendation||x.action||x.fix||defaultRecommendation(category);const context=x.context||x.anchor_text||x.details||'';const recordId=x.record_id||x.record||'';const id=x.id||`scan:${stableId([fileName,category,severity,pageUrl,targetUrl,title,index].join('|'))}`;return{id,recordId,title:String(title),category,severity,summary:String(summary),recommendation:String(recommendation),context:String(context),pageUrl:String(pageUrl),targetUrl:String(targetUrl),replacementUrl:String(replacementUrl),sourceType:x.source_type||x.source||fileName};}
function normalizeCategory(value){const text=String(value||'').toLowerCase();if(text.includes('broken'))return'broken';if(text.includes('redirect'))return'link-maintenance';if(text.includes('source'))return'unsourced';if(text.includes('meta'))return'metadata';if(text.includes('opportun'))return'link-opportunity';if(text.includes('review'))return'review';return text.replace(/[^a-z0-9]+/g,'-')||'imported';}
function normalizeSeverity(value,status,category){const text=String(value||'').toLowerCase();if(['high','medium','low'].includes(text))return text;const code=Number.parseInt(status||'',10);if(category==='broken'||code>=500)return'high';if(code>=400||category==='unsourced'||category==='metadata')return'medium';return'low';}
function defaultRecommendation(category){if(category==='broken')return'Repair, replace, or remove the failing link.';if(category==='link-maintenance')return'Update the page to use the final destination directly.';if(category==='unsourced')return'Add a documented source or curatorial note.';if(category==='metadata')return'Complete the missing metadata.';if(category==='link-opportunity')return'Add the relevant internal link where it improves navigation.';return'Review and resolve this imported finding.';}
function parseCsvFindings(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const headers=splitCsv(lines[0]).map(h=>h.trim());return lines.slice(1).map(line=>{const cells=splitCsv(line);return Object.fromEntries(headers.map((h,i)=>[h,cells[i]||'']));});}
function splitCsv(line){const out=[];let cell='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){out.push(cell);cell='';}else cell+=c;}out.push(cell);return out;}
function backup(){download({exportedAt:new Date().toISOString(),records,scanFindings},`curatoros-backup-${new Date().toISOString().slice(0,10)}.json`);}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function metric(n,labelText){return`<div class="metric"><strong>${n}</strong><span>${esc(labelText)}</span></div>`;}
function haystack(x){return[x.title,x.summary,x.recommendation,x.context,x.pageUrl,x.targetUrl,x.replacementUrl,x.recordId,x.category,x.severity,x.sourceType].join(' ').toLowerCase();}
function dedupe(items){return[...new Map(items.map(x=>[x.id,x])).values()];}
function stableId(value){let hash=2166136261;for(const char of String(value||'')){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return(hash>>>0).toString(16);}
function readJson(key,fallback){try{const value=JSON.parse(localStorage.getItem(key)||'null');return value??fallback;}catch{return fallback;}}
function label(value){return String(value||'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
render();