const RF_KEY='curatoros.research.focus';
const rfStyle=document.createElement('style');rfStyle.textContent=`.research-focus-target{outline:2px solid var(--accent,#bfa46a)!important;outline-offset:4px;box-shadow:0 0 0 6px rgba(191,164,106,.12),0 12px 30px rgba(0,0,0,.28)!important;animation:research-focus-pulse 1.4s ease-out 1}@keyframes research-focus-pulse{0%{outline-offset:10px}100%{outline-offset:4px}}`;document.head.append(rfStyle);
window.addEventListener('curatoros:workspace-opened',()=>setTimeout(rfApply,20));
document.addEventListener('click',event=>{const target=event.target.closest?.('#research-queue,#conclusion-review,#knowledge-promotion,#incorporation-review');if(target)setTimeout(rfApply,40)},true);
setTimeout(rfApply,100);

function rfRead(){try{return JSON.parse(sessionStorage.getItem(RF_KEY)||'null')}catch{return null}}
function rfApply(){const f=rfRead();if(!f?.workspace||!f?.id)return;const active=document.querySelector('.nav .active');if(!active||active.id!==f.workspace)return;if(f.workspace==='research-queue')return rfQueue(f);if(f.workspace==='conclusion-review')return rfConclusion(f);if(f.workspace==='knowledge-promotion')return rfPromotion(f);if(f.workspace==='incorporation-review')return rfIncorporation(f)}
function rfQueue(f){const status=document.querySelector('#rq-filter');if(status&&status.value!=='all'){status.value='all';status.dispatchEvent(new Event('change',{bubbles:true}));return setTimeout(rfApply,25)}const type=document.querySelector('#rq-type');if(type&&type.value!=='all'){type.value='all';type.dispatchEvent(new Event('change',{bubbles:true}));return setTimeout(rfApply,25)}const notebook=document.querySelector(`[data-rq-notebook="${rfCss(f.id)}"]`);if(notebook){const card=notebook.closest('.research-task');if(f.kind==='notebook'){notebook.click();setTimeout(()=>rfFinish(document.querySelector('#rq-investigation-notebook')||card),30)}else rfFinish(card);return}rfRetry()}
function rfConclusion(f){const filter=document.querySelector('#cr-filter');if(filter&&filter.value!=='all'){filter.value='all';filter.dispatchEvent(new Event('change',{bubbles:true}));return setTimeout(rfApply,25)}const anchor=document.querySelector(`[data-cr-id="${rfCss(f.id)}"]`);if(anchor)return rfFinish(anchor.closest('.conclusion-review-card'));rfRetry()}
function rfPromotion(f){const filter=document.querySelector('#kp-filter');if(filter&&filter.value!=='all'){filter.value='all';filter.dispatchEvent(new Event('change',{bubbles:true}));return setTimeout(rfApply,25)}const anchor=document.querySelector(`[data-kp-save="${rfCss(f.id)}"]`);if(anchor)return rfFinish(anchor.closest('.kp-card'));rfRetry()}
function rfIncorporation(f){const filter=document.querySelector('#ir-filter');if(filter&&filter.value!=='all'){filter.value='all';filter.dispatchEvent(new Event('change',{bubbles:true}));return setTimeout(rfApply,25)}const card=document.querySelector(`[data-ir-package="${rfCss(f.id)}"]`);if(card)return rfFinish(card);rfRetry()}
function rfFinish(el){if(!el)return rfRetry();document.querySelectorAll('.research-focus-target').forEach(x=>x.classList.remove('research-focus-target'));el.classList.add('research-focus-target');el.scrollIntoView({behavior:'smooth',block:'center'});try{sessionStorage.removeItem(RF_KEY)}catch{}setTimeout(()=>el.classList.remove('research-focus-target'),4500)}
function rfRetry(){const f=rfRead();if(!f)return;const age=Date.now()-Date.parse(f.requestedAt||0);if(!Number.isFinite(age)||age<2500)setTimeout(rfApply,80);else try{sessionStorage.removeItem(RF_KEY)}catch{}}
function rfCss(v){return CSS.escape(String(v||''))}
