const CATALOG_KEY='curatoros.rebuilt.catalog';
const RD_STATE_KEY='curatoros.research.desk.state';
const app=document.querySelector('#app');
const button=document.querySelector('#research-desk');
button?.addEventListener('click',()=>{activate();render();});
window.addEventListener('curatoros:records-changed',()=>{if(button?.classList.contains('active'))render();});
function activate(){document.querySelectorAll('.nav .active').forEach(el=>el.classList.remove('active'));button?.classList.add('active');}
function readRecords(){try{const v=JSON.parse(localStorage.getItem(CATALOG_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function rdState(){try{const v=JSON.parse(localStorage.getItem(RD_STATE_KEY)||'{}');return v&&typeof v==='object'?v:{}}catch{return{}}}
function rdSave(v){localStorage.setItem(RD_STATE_KEY,JSON.stringify(v));}
function ships(){return readRecords().filter(r=>r?.type==='ship'||String(r?.id||'').startsWith('ship:'))}
function title(r){return r?.title||r?.name||r?.id||'Untitled record'}
function vals(v){if(Array.isArray(v))return v.flatMap(vals).filter(Boolean);if(v&&typeof v==='object')return vals(v.name||v.value||v.label||'');return v==null?[]:[String(v).trim()].filter(Boolean)}
function field(r,...keys){for(const k of keys){const v=r?.data?.[k];if(vals(v).length)return v}return''}
function norm(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function groupBy(records,keys,label){const map=new Map();for(const r of records){for(const v of vals(field(r,...keys))){const k=norm(v);if(!k)continue;if(!map.has(k))map.set(k,{label,value:String(v),records:[]});map.get(k).records.push(r)}}return [...map.values()].filter(g=>g.records.length>=2).sort((a,b)=>b.records.length-a.records.length)}
function analyze(){const s=ships();const builders=groupBy(s,['builder'],'Builder');const operators=groupBy(s,['originalOperator','operator'],'Operator');const routes=groupBy(s,['routes','routeFocus'],'Route');const classes=groupBy(s,['shipClass','class'],'Class');const registries=groupBy(s,['registry','country'],'Registry');const eras=new Map();for(const r of s){const raw=vals(field(r,'launchDate','completedDate'))[0];const year=Number(String(raw||'').match(/\b(18|19|20)\d{2}\b/)?.[0]);if(year){const decade=Math.floor(year/10)*10;const k=`${decade}s`;if(!eras.has(k))eras.set(k,[]);eras.get(k).push(r)}}const eraGroups=[...eras].map(([value,records])=>({label:'Era',value,records})).filter(g=>g.records.length>=2).sort((a,b)=>b.records.length-a.records.length);const groups=[...builders,...operators,...routes,...classes,...registries,...eraGroups];const intersections=[];for(let i=0;i<groups.length;i++)for(let j=i+1;j<groups.length;j++){if(groups[i].label===groups[j].label)continue;const b=new Set(groups[j].records.map(r=>r.id));const common=groups[i].records.filter(r=>b.has(r.id));if(common.length>=2)intersections.push({a:groups[i],b:groups[j],records:common,score:common.length});}intersections.sort((a,b)=>b.score-a.score);const thin=groups.filter(g=>g.records.length===2||g.records.length===3).slice(0,20);return{s,builders,operators,routes,classes,registries,eraGroups,intersections:intersections.slice(0,30),thin};}
function render(){if(!app)return;const a=analyze(),state=rdState();const saved=Object.values(state).filter(x=>x.status==='saved').length;const investigating=Object.values(state).filter(x=>x.status==='investigating').length;app.innerHTML=`<section class="panel research-desk-hero"><span class="eyebrow">Corpus discovery · Research Desk</span><h3>What does CuratorOS see?</h3><p>This workspace looks across canonical Ship Records for recurring patterns, useful intersections, and small clusters that may deserve investigation. These are prompts from the corpus—not historical conclusions.</p><div class="research-desk-stat"><strong>${a.s.length}</strong><span>ship records considered</span></div><div class="research-desk-stat"><strong>${saved}</strong><span>saved discoveries</span></div><div class="research-desk-stat"><strong>${investigating}</strong><span>being investigated</span></div></section><nav class="panel research-desk-jumps"><a href="#rd-patterns">Strong patterns</a><a href="#rd-intersections">Interesting intersections</a><a href="#rd-small">Small clusters</a></nav><section class="panel" id="rd-patterns"><span class="eyebrow">Strong patterns</span><h4>Recurring structures in the corpus</h4><div class="research-desk-grid">${[...a.builders.slice(0,5),...a.operators.slice(0,5),...a.routes.slice(0,5),...a.classes.slice(0,5),...a.eraGroups.slice(0,5)].sort((x,y)=>y.records.length-x.records.length).slice(0,20).map(groupCard).join('')||'<p class="empty">Not enough structured overlap yet.</p>'}</div></section><section class="panel" id="rd-intersections"><span class="eyebrow">Interesting intersections</span><h4>Where two patterns overlap</h4><p class="research-desk-note">Intersections can expose comparison sets that are easy to miss when records are viewed one ship at a time.</p><div class="research-desk-grid">${a.intersections.map(intersectionCard).join('')||'<p class="empty">No multi-pattern intersections yet.</p>'}</div></section><section class="panel" id="rd-small"><span class="eyebrow">Research seeds</span><h4>Small clusters worth a closer look</h4><p class="research-desk-note">A cluster of only two or three ships is not automatically important—but it can be exactly where an interesting research question begins.</p><div class="research-desk-grid">${a.thin.map(groupCard).join('')||'<p class="empty">No small structured clusters yet.</p>'}</div></section>`;bind();}
function keyFor(kind,a,b=''){return `${kind}|${norm(a)}|${norm(b)}`}
function groupCard(g){const key=keyFor(g.label,g.value),q=questionFor(g),s=rdState()[key]?.status||'';return `<article class="research-desk-card"><div class="badges"><span class="badge">${esc(g.label)}</span><span class="badge">${g.records.length} ships</span>${s?`<span class="badge">${esc(s)}</span>`:''}</div><h4>${esc(g.value)}</h4><p>${esc(q)}</p><div class="research-desk-members">${members(g.records)}</div>${actions(key,q,g.records)}</article>`}
function intersectionCard(x){const key=keyFor('Intersection',x.a.value,x.b.value),q=`What, if anything, does this shared ${x.a.label.toLowerCase()} and ${x.b.label.toLowerCase()} context reveal about these ships?`,s=rdState()[key]?.status||'';return `<article class="research-desk-card"><div class="badges"><span class="badge">Intersection</span><span class="badge">${x.records.length} ships</span>${s?`<span class="badge">${esc(s)}</span>`:''}</div><h4>${esc(x.a.value)} × ${esc(x.b.value)}</h4><p>${esc(q)}</p><div class="research-desk-members">${members(x.records)}</div>${actions(key,q,x.records)}</article>`}
function actions(key,q,records){return `<div class="research-desk-actions"><button type="button" data-rd-save="${esc(key)}" data-rd-question="${esc(q)}">Save idea</button><button type="button" data-rd-start="${esc(key)}" data-rd-question="${esc(q)}">Investigate</button>${records.length===1?`<button type="button" data-rd-open="${esc(records[0].id)}">Open record</button>`:''}</div>`}
function bind(){document.querySelectorAll('[data-rd-save]').forEach(b=>b.addEventListener('click',()=>setStatus(b.dataset.rdSave,'saved',b.dataset.rdQuestion)));document.querySelectorAll('[data-rd-start]').forEach(b=>b.addEventListener('click',()=>setStatus(b.dataset.rdStart,'investigating',b.dataset.rdQuestion)));document.querySelectorAll('[data-rd-open]').forEach(b=>b.addEventListener('click',()=>{sessionStorage.setItem('curatoros.openRecordId',b.dataset.rdOpen);window.CuratorOSNavigate?.open?.('records')}));}
function setStatus(key,status,question){const s=rdState();s[key]={...(s[key]||{}),status,question,updatedAt:new Date().toISOString()};rdSave(s);render();}
function questionFor(g){const n=g.records.length;if(g.label==='Builder')return `What design, engineering, or commercial patterns emerge across these ${n} ships from the same builder?`;if(g.label==='Operator')return `How do these ${n} ships illuminate the fleet strategy or service priorities of this operator?`;if(g.label==='Route')return `What changed—and what remained consistent—across ships associated with this service?`;if(g.label==='Class')return `How closely did these sister or class-related ships actually resemble one another in service and outcome?`;if(g.label==='Era')return `What does this group reveal about liner design and operation during the ${g.value}?`;return `Is this shared ${g.label.toLowerCase()} meaningful enough to support a comparison or research collection?`}
function members(records){const names=records.slice(0,8).map(r=>`<span>${esc(title(r))}</span>`).join('');return names+(records.length>8?`<span>+${records.length-8} more</span>`:'')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
